name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
       
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: list before build
        run: ls -al
      - name: Build app
        run: npm run build
      - name: list after build
        run: ls -al
      - name: list inside build
        run: ls ./dist
      - name: Run tests
        run: npm test
      - name: list after lest
        run: ls -al
        
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Delete old build files
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ${{ secrets.EC2_HOST }}@${{ secrets.EC2_USERNAME }} "rm -rf /var/myapp/dist"
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist"
          target: "/var/myapp"
      
      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/myapp
            pm2 restart main.js
